vim.keymap.set({ "n", "v", "x" }, ";", ":")
vim.keymap.set("n", "s", "<nop>")
vim.keymap.set("n", "S", ":w<CR>")
vim.keymap.set("n", "Q", ":q<CR>")
vim.keymap.set("n", "<A-s>k", ":e $MYVIMRC<CR>")
vim.keymap.set("n", "sr", ":source $MYVIMRC<CR>")
vim.keymap.set("n", "sh", ":set nosplitright<CR>:vsplit<CR>")
vim.keymap.set("n", "sk", ":set splitright<CR>:split<CR>")
vim.keymap.set("n", "sj", ":set nosplitright<CR>:split<CR>")
vim.keymap.set("n", "st", ":tabe<CR>")
vim.keymap.set("n", "si", ":+tabnext<CR>")
vim.keymap.set("n", "su", ":-tabnext<CR>")
vim.keymap.set("n", "<SPACE>q", ":qa<CR>")
vim.keymap.set("n", "<SPACE>j", "<C-w>j")
vim.keymap.set("n", "<SPACE>k", "<C-w>k")
vim.keymap.set("n", "<SPACE>h", "<C-w>h")
vim.keymap.set("n", "<SPACE>l", "<C-w>l")
vim.keymap.set("n", "<SPACE>sp", ":set spell!<CR>")
vim.keymap.set("n", "<Up>", ":res +5<CR>")
vim.keymap.set("n", "<Down>", ":res -5<CR>")
vim.keymap.set("n", "<Left>", ":vertical resize+5<CR>")
vim.keymap.set("n", "<Right>", ":vertical resize-5<CR>")
vim.keymap.set("v", "<C-c>", [["+y]])
vim.keymap.set("n", "<C-p>", [["+p]])
vim.keymap.set("n", "<C-p>", "<C-r>+")
vim.keymap.set({ "n", "v" }, ">", ">gv")
vim.keymap.set({ "n", "v" }, "<", "<gv")
vim.keymap.set("v", "p", '"_dP')
vim.keymap.set("n", "sD", ":bd!<CR>")
